### ISSUE TITLE
Auto response for VT-x questions on Morpheus' server #24

### ISSUE THREAD

**Issue by AdriDevelopsThings** [PyDrocsid/MorpheusHelper#1]
Is your feature request related to a problem? Please describe.
Es geht bestimmt vielen Leuten auf den Sack, dass immer wieder Fragen über die Installation von Kali fragen, vor allem weil das eigentlich immer die selbe Frage ist.

Describe the solution you'd like
Der Bot soll in jeder neuen Nachricht, welche in #hacking gefragt/gesagt wird, nach den Wörtern
"VT-x"/"Virtualisierung" + "Virtualbox" oder "Installation" + "Kali" oder sowas ähnliches suchen.
Beinhaltet eine Nachricht diese Wörter, so wird automatisch eine die Antwort geschickt.

Describe alternatives you've considered
Der Bot könnte als Alternative immer den gidf Link als Antwort schicken. (ist eventuell ein bisschen Provozierend, aber egal xD)

Additional context
I use Arch btw.

Orginalissue: https://github.com/AdriBloober/DiscordSearchBot/issues/24
Ist hier in dem Bot glaube ich passender ^^

**Comment by AdriBloober** [comment]
Assign ich mir hiermit mal selber loool

**Comment by Defelo** [comment]
> Assign ich mir hiermit mal selber loool

so, jetzt bist du assigned. enttäusch mich nicht!
